### ISSUE TITLE
No title for sxiv image viewer

### ISSUE THREAD

**Issue by freecsu** [psifidotos/applet-window-title#28]
No title is displayed at all (not even the 'Default' text) when the image viewer 'sxiv' is the active window. Is there a possible fix for this?

**Comment by psifidotos** [comment]
1. What is the window title bar text?
2. Normal plasma taskmanager what text does it show for it?

**Comment by freecsu** [comment]
The titlebar text is "sxiv - /path/to/file.img" which is the same text shown on the taskmanager applet.

**Comment by psifidotos** [comment]
Show me a screenshot please

**Comment by freecsu** [comment]
![screenshot_20181130_113027](https://user-images.githubusercontent.com/45189486/49301878-a88d4300-f493-11e8-8b8b-01c6bea6a2fa.png)
![screenshot_20181130_113212](https://user-images.githubusercontent.com/45189486/49301909-b80c8c00-f493-11e8-8e87-423db033c6c9.png)
The first image shows the default title with no active window. The second image shows the lack of title with a sxiv window active.

**Comment by psifidotos** [comment]
@freecsu how this can be solved and what is needed from you:

1. plasma libtaskmanager does not detect properly the appName for sxiv, you can report this at bugs.kde.org if you want. If you want to solve it yourself you can add at sxiv desktop file the following record:

`StartupWMClass=sxiv`

2. afterwards you can use latest git version or upcoming 0.3 version in order to show title properly

**Comment by psifidotos** [comment]
reported [1] at plasma: https://bugs.kde.org/show_bug.cgi?id=402762
