### ISSUE TITLE
[Feature] Display title of inactive windows

### ISSUE THREAD

**Issue by trmdi** [psifidotos/applet-window-title#30]
You can display `applet-window-buttons` and `applet-window-appmenu` with inactive windows, but currently this applet doesn't provide such an option.

![image](https://user-images.githubusercontent.com/11857205/50371536-57362680-05ef-11e9-94d1-9cd7e8382212.png)
E.g. It should display "Dolphin" instead of "Plasma desktop <3"

**Comment by psifidotos** [comment]
I am not sure this is this applet's issue... For example at described use case the applet window buttons are shown because they are set Always Visible but they don't interact with the shown inactive window.

Supporting inactive windows per screen makes things complicated there is a big chance all inactive windows functionality to be dropped from applets

**Comment by trmdi** [comment]
In the "always display" mode of the applets, can you make them connect with the last active window ?
It would be more consistent with `applet-window-appmenu`.

This could also fix https://github.com/psifidotos/applet-window-title/issues/21

**Comment by psifidotos** [comment]
> This could also fix #21

no it couldnt. plasma libtaskmanager filters subdialogs so this is irrelevant... #21 can be fixed only if a c++ library is provided that behaves as a small window manager just like what Latte is doing for its visibility modes. This would have an impact that applet-window-title should not be a qml-only applet.

The use case you are describing has consequences that do not take into account the global menu limitations. The global menu infrastructure can show only one app menu at each time and that could be only the active window one or the last active window one if the new active window does not provide any app menu. In multi-screen environment that is a mess.

So in any case I could accept patches that take into account the above considerations and solve the mentioned issue but I personally wouldnt  try to follow that road because it is probably a dead end.

In my system, in order to handle all the above limitations and also provide a nice multi-screen experience the applets have the following visibility modes:
1. Window Title: Show Only window information from current screen
2. Window AppMenu: Show only menus from current screen, show only menus from active applications
3. Window Buttons: Active Window is present
