### ISSUE TITLE
Application icon painting

### ISSUE THREAD

**Issue by azazello4** [psifidotos/applet-window-title#40]
Using latest Latte git version and latest window Title Applet;
- Kubuntu 18.10, Plasma 5.15;

I don't think the application icon should be painted when using the auto-coloring feature. I'd prefer to see the icon with its color, instead of a grey blob.
Is it possible to paint only the application name, and not the icon?

**Comment by azazello4** [comment]
It seems that disabling the tooltip painting allows to paint only the text, doesn't it?

**Comment by psifidotos** [comment]
> Using latest Latte git version and latest window Title Applet;

I am not that sure, either Latte is behind of commits or Window Title Applet in your system. Window Title Applet since v0.3 supports this properly...

If it was working correctly in your system then Latte shouldnt give you even the choice to enable/disable painting because Latte is informed that this applet supports it fully...

**Comment by psifidotos** [comment]
1. what is the last commit used from Latte dock?
2. what is your window title applet version?

**Comment by azazello4** [comment]
A reboot fixed it.

**Comment by psifidotos** [comment]
;)
