### ISSUE TITLE
Libreoffice not showing app title

### ISSUE THREAD

**Issue by Spinnekop** [psifidotos/applet-window-title#75]
Displays as soffice.bin rather than Writer or Impress

**Comment by psifidotos** [comment]
You can blame libreoffice for this... You will have the same issue with any alternative.

**Comment by Spinnekop** [comment]
![image](https://user-images.githubusercontent.com/31868152/67903993-f65b7100-fb64-11e9-8027-86c977f19536.png)
This is my latte top panel with windows title left and active window manager right. awm shows the correct title so not the same issue with any alternative.

**Comment by psifidotos** [comment]
1. Latte version
2. Plasma version
3. A screenshot with plasma taskmanager with previews enabled, what does it show the preview for libreoffice

**Comment by Spinnekop** [comment]
Hello Michail

Active Windows Control does in fact show the real title and icon as per the
screenshot I added to the issue. However, it doesn't work with global menu
so it's a trade-off I am prepared to make!!

Thanks for you work on latte!!

Best wishes

Paul

**Comment by psifidotos** [comment]
following the code path the bug is in Latte, https://bugs.kde.org/show_bug.cgi?id=413671 I will try to handle the case and you can follow the Latte bug report for updates. When the Window Title is inside Latte it uses the Latte infrastructure to track application name and icon. And Latte infrastructure for this state it currently breaks.

**Comment by psifidotos** [comment]
@Spinnekop it is going to be fixed with Latte v0.9.5 , if you build Latte on your own you could already test it

**Comment by Spinnekop** [comment]
Super - thank you. I will do that!
