### ISSUE TITLE
Request: Option to continue to display when using "Show Window AppMenu applet on mouse enter"

### ISSUE THREAD

**Issue by AndydeCleyre** [psifidotos/applet-window-title#80]
The behavior I would like to achieve:
- Text style: Do not show any text
- Show Window AppMenu applet on mouse enter
- Continue to show Window Title applet on mouse enter as well
- Continue to show Window AppMenu applet while mouse is over Window AppMenu -- This part is for the other applet, I guess, and may already be the case. I just don't want the menu to disappear as I try to use it.

One path to this would be to have another toggle option available only when "Show Window AppMenu applet on mouse enter" is enabled, like "Continue to show this applet."

Another would be to add icon/title functionality to the other applet.

I would really like the AppMenu to be accompanied by some signifier of *which* app it controls.

```
plasma5-applets-window-title 0.5.2
plasma5-applets-window-appmenu 0.6.0
```

**Comment by psifidotos** [comment]
I don't think I am interested in any of the requests.

Especially adding window title, icon capabilities to AppMenu on its own, I don't think I will ever support it.

Concerning Window Title to stay visible this is not as simple as you describe it. In order to be a user enhancement then the applet should fill the entire free space when no appmenu is shown and when the appmenu is shown then is should use a maximum length value, and all this should also track the mouse hovering for both applets is order to identify when the appmenu must become hidden... Too much logic and complexity for just a small demanded feature...

**Comment by AndydeCleyre** [comment]
> the applet should fill the entire free space when no appmenu is shown and when the appmenu is shown then is should use a maximum length value

Can you expand on this? I'm not sure I understand. Ideally when only the icon is shown, the applet takes as much space as the icon width, and when the menu is also shown, the combined space used by the two applets are the length of the menu plus the icon width.

**Comment by psifidotos** [comment]
Sorry, no interest elaborating any further, if you feel you can provide commits for review, feel free to do so,i will be more than happy reviewing them.
