### ISSUE TITLE
[Feature request] Add "Fixed width" option

### ISSUE THREAD

**Issue by trmdi** [psifidotos/applet-window-title#87]
I think when "Fill available space" is checked, the applet should always takes a fixed width which is set as the maximum value.

This is needed for the layout like this: `[Panel: [Title] [Plasma TaskManager]     ]`
Because it will give Taskmanager a fixed position.

**Comment by th3hamm0r** [comment]
That would be nice! In my case I'm switching from Unity to Plasma. I have window buttons, window title (icon + title) and a following global menu.
The global menu often jumps, if the window-title is too short, a fixed width would help here.

**Comment by psifidotos** [comment]
Ifyou use Window AppMenu with Window Title in a Latte panel you can replicate the original Unity behavior, meaning that you can show the appmenu only when Window Title is hovered.

**Comment by th3hamm0r** [comment]
Thanks, good to know!
But actually, I like my new setup with a persistent, always visible title + appmenu even more ;), because I can find menus more quickly. Only the moving title (without the fixed width) is not perfect yet, so that would be nice. 
But anyway I have to thank you for your awesome work!
